### ISSUE TITLE
Few glitches with includegraphics etc.

### ISSUE THREAD

**Issue by sambo57u** [ftilmann/latexdiff#106]
Hi,

Using the latest from CTAN I have few issues:

1. The "*" star option for includegraphics is not recognized i.e. includegraphics*[]{}

2. The construction $^{92}$Kr$+$$^{208}$Pb is confusing latexdiff because of $$ which is really
    two single $'s. This is understood by latex.

Thank you very much for this great program.

**Comment by ftilmann** [comment]
Next time please raise separate issues for different issues. 
1. I need some clarification, can you construct an MWE (minimum working example)
2. I will not bother fixing - while technically correct, it is a niche construction, and the amount of effort involved in addressing this is disproportionate to its importance (in my opinion, of course).

**Comment by sambo57u** [comment]
Hi, for some reason when I tried MWE it worked. I will keep an eye on this further and see if I can come up with a MWE. I agree with the #2 it is a weird construct due to journal requirement. I need to start
writing it as $^{92}\mathrm{Kr}+^{208}\mathrm{Pb}$.

**Comment by ftilmann** [comment]
Ok I will close this for now based on your comments - you can still post in this thread if you come up with an MWE that demonstrates your first issue, and I will reopen
