### ISSUE TITLE
latexdiff-vc with hg option does not extract previous revision correctly

### ISSUE THREAD

**Issue by ouboub** [ftilmann/latexdiff#115]
Hi

running ubuntu 14.04 I just cloned on a different laptop the git repo.
I do

make distribution 
cd dist
make install

then I run 
/usr/local/bin/latexdiff-vc  --so  --math-markup=2 --hg eulerpoisson.tex -r 272

and obtain

Working on  eulerpoisson.tex 
hg diff: option --root not recognized
patch: **** Only garbage was found in the patch input.
One or both of the files to compare are empty. Possibly something went wrong in the retrieval of older versions. Aborting ...

while the same installation on a different Ubuntu 14.04 works flawlessly.The input file is ok, the tmp file however is emtpy
what is wrong here?

thanks

Uwe Brauer

**Comment by ftilmann** [comment]
As I did not implement the hg functionality and have never tested or used it, I cannot help immediately but it strikes me as something easy to fix. @junghans  provided the pull request for this feature, I hope he is still listenening. 
If you say it works on one computer, but not the other, all I can really think of that different versions of hg (mercurial) are installed on both, and support for option --root was added or subtracted. 

Can you try to manually extract the diff (patch) file on both computers:
`
hg diff --root . -r272  eulerpoisson.tex  > eulerpoisson.tex.patch
`
If you simply leave out the root option, does it work?   If you let me know how I can generate the patch file (diff file) in hg to a chosen version, the required change to latexdiff-vc should be trivial

**Comment by junghans** [comment]
@ouboub: Can you compare the output of `hg version`? I guess, on the one system you are having an `hg` with the `--root` option.

You could check if the option exists with:
```
hg diff --help | grep root
```

**Comment by ouboub** [comment]
Hi to both  of you

thanks for the fast answer, indeed on the other laptop mercurial was very old vs 2.8 and did not support the root option. Upgrading mercurial solved the problem. So please close the issue. thanks

Uwe

**Comment by junghans** [comment]
@ftilmann : Could you mention in docs that `latexdiff-vcs` now needs an h`hg` version newer than 2.8?
