### ISSUE TITLE
! Argument of \UL@word has an extra }.

### ISSUE THREAD

**Issue by foice** [ftilmann/latexdiff#117]
```
Underfull \vbox (badness 8038) has occurred while \output is active
! Argument of \UL@word has an extra }.
<inserted text>
                \par
l.233 \begin{equation}
```

I have already passed the two files under dos2unix ... any further idea?

**Comment by ftilmann** [comment]
Unfortunately, this is impossible to answer with an MWE (minimum working example).  Unless you can identify a clear bug or missing feature it might be better to ask this in Stack Exchange (you will need an MWE there as well). I will close this for now but feel free to open a new issue with a narrower problem definition.
