### ISSUE TITLE
Potentially greedy pattern for listings

### ISSUE THREAD

**Issue by jprotze** [ftilmann/latexdiff#119]
I have an issue with really long runtime (aborted after several minutes) for a long document with multiple listings. I could fix it by the following change:

https://github.com/ftilmann/latexdiff/blob/master/latexdiff#L2994
```
- ((?:\%\Q$DELCOMMENT$VERBCOMMENT\E.*?\n)*)
+ ((?:\%\Q$DELCOMMENT$VERBCOMMENT\E[^\n]*?\n)*)
```

I think the intention is, that the pattern should not match across multiple lines?
The alternative would be using a negative look-ahead (instead of the .), to avoid running out of the environment.

**Comment by ftilmann** [comment]
Wow, how did you track that one down? I would have thought that the minimal matching operator would have implied the non-newline interpretation of "." but apparently not. 
On my test files, there was no noticeable effect on either output or runtime, but as it seems to help in your case and no adverse effect are known  I implemented that exactly as suggested in commit   
32decf1
