### ISSUE TITLE
Changes in verbatim/listings environment don't generate a zlabel

### ISSUE THREAD

**Issue by jprotze** [ftilmann/latexdiff#134]
```
\documentclass{book}
\usepackage{listings}
\usepackage{blindtext}
\begin{document}
\Blindtext
\begin{lstlisting}
typedef struct {
  int a;
} A;
\end{lstlisting}
\Blindtext
\end{document}
```
```
\documentclass{book}
\usepackage{listings}
\usepackage{blindtext}
\begin{document}
\Blindtext
\begin{lstlisting}
typedef struct {
  int a;
  int b;
} A;
\end{lstlisting}
\Blindtext
\end{document}
```
This is how I try to create the minimal diff:
`latexdiff-vc --only-changes --pdf code1.tex code2.tex`

The expected result is a pdf containing 1 page with the diff. The actual result is a pdf with all 3 pages.

My solution proposed in PR #132 is to intoduce a new command to mark changes in verbatim environments. This command works like \DIFaddbegin, but does not exactly mark the begin of a modification. Just says "something changed here".

**Comment by ftilmann** [comment]
I have merged the commit. Thanks and sorry it has taken so long
