### ISSUE TITLE
I need help：   latexdiff original.tex  revised.tex>diff.tex

### ISSUE THREAD

**Issue by linzgood** [ftilmann/latexdiff#135]
D:\Program Files (x86)\CTEX\MiKTeX\scripts\latexdiff>
I   input   ：    ## **latexdiff original.tex  revised.tex>diff.tex**
## **Malformed UTF-8 character (fatal) at D:\Program Files (x86)\CTEX\UserData\scripts\latexdiff\latexdiff line 1387.**

**Comment by linzgood** [comment]
I am sure “latexdiff”  is good.  The errors are in the revised.tex.  But， I don‘’t know how correct it.

**Comment by ftilmann** [comment]
In case this is still of interest: in this case I usually proceed by building up the fault file bit by bit, e.g. just start with the preamble, and then copy parts of the offending text, in each cases trying until the error occurs (or uncomment more and more of the original text until it runs). By going to smaller and smaller chunks, you can isolate the bad line - I know this sounds tedious, and it is, but this is what I do.  Once you have identified the line, hopefully a funny character shows up in the editor, which you could simply delete. Sometimes, the offending character is not easily visible; it can help to delete the line completely and type it in again (not use copy/paste). I had weird mistakes cleared out in this way. 

But before you do that, check the encoding of the text with some other program and make sure 
(I only have access to linux, so it would be difficult for me to test directly). If it's some other encoding, try setting that explicity with `--encoding` option.  I will close the issue as I don't think I can contribute anymore - if you get stuck and can offer more information feel free to reopen.
