### ISSUE TITLE
Extra }, or forgotten $.

### ISSUE THREAD

**Issue by mktippett** [ftilmann/latexdiff#137]
Latexdiff is a super great tool! So when it gives a tex file with errors, I'm lost.
I've attached an old file, a new file and what latexdiff gives. 
I think that the problem is that \end{equation} is commented out, but I'm not sure.
I'm using this version. Thanks!
latexdiff --version
This is LATEXDIFF 1.2.0  (Algorithm::Diff 1.15 so, Perl v5.18.2)
  (c) 2004-2016 F J Tilmann

[example.zip](https://github.com/ftilmann/latexdiff/files/1695995/example.zip)

**Comment by ftilmann** [comment]
I can confirm this bug with latexdiff 1.2.0.  I have tested this with the current github version, and then the problem is solved and it works.
 So you either upgrade directly from github or wait until 1.2.2 is released. (I did not test 1.2.1, so maybe already this works)
