### ISSUE TITLE
Intertext

### ISSUE THREAD

**Issue by MDTF** [ftilmann/latexdiff#138]
First of all, I love latexdiff! I just wanted to mention the fact that it doesn't work well with \intertext. If an intertext is added or removed from an \align-environment, latexdiff will change it to \DIFadd{\intertext{...}}. This doesn't compile right; I think it should be \intertext{\DIFadd{...}}.

**Comment by ftilmann** [comment]
I cannot reproduce this behaviour with vanilla latexdiff: instead, it simply comes up as \DIFaddbegin \intertext{...} \DIFaddend, i.e. the standard behaviour of not marking up unknown latex commands is employed by latexdiff (I have tested this with the version on github, but I believe it should work with the release version as well), and this compiles, of course.
To actually get the desired behaviour, you can use `--append-textcmd=intertext`  (I have added this to the default list of text commands with commit 9e76ff , so this option will only be needed until the next update)
