### ISSUE TITLE
Unescaped left brace in regex is deprecated... latexdiff-git LINE 451

### ISSUE THREAD

**Issue by ExtremOPS** [ftilmann/latexdiff#140]
Hi,

I am using `latexdiff-git --exclude-textcmd="section,subsection,subsubsection" --math-markup=2 --flatten -r $LAST_GOOD_SHA $tex` to create a certain `diff` file. But I get following errors:

`Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\zref\@newlabel{ <-- HERE DIFchgb(\d*)}{.*\\abspage{(\d*)}}/ at /usr/bin/latexdiff-git line 451.`

and some more `Unescaped left brace in regex is deprecated, passed through in regex; marked by` errors down the road in `latexdiff`.

**Comment by ftilmann** [comment]
Thanks for the report. The issue with the left braces has been fixed on github - you will have to wait for the next version update or install from github.  
The 'deprecated' warning in itself should not result in error, though, so maybe something else is wrong? If so, please open a new issue with detailed description and MWE.
