### ISSUE TITLE
Suggestion: default versions for latexdiff-vc

### ISSUE THREAD

**Issue by briochemc** [ftilmann/latexdiff#150]
First of all I have to say I love this script - it works great and simplifies a lot of work for me.
I was wondering if it is possible (or even a good idea) to have some default revisions for `latexdiff-vc` in case the revisions are not supplied as input, so that, e.g.,
```
latexdiff-vc manuscript.tex
```
choses the current HEAD and the previous commit as versions to make the diff of. That is, if HEAD is currently at commit hash `95244a9` and its parent is `3db2b37`, The short command above does the same as
```
latexdiff-vc -r 3db2b37 -r 95244a9 manuscript.tex
```
I am not even sure I am wording all this correctly, but I thought I'd give it a go, as the diff between the HEAD and its parent is what I use most. It would also make for a very short (and user-friendly) command to get a nice latexdiff of the latest changes! 😃

**Comment by ftilmann** [comment]
This more or less exists already. You get the default by selecting -r option without any argument, e.g.
```
latexdiff-vc -r manuscript.tex
```
will compare the current version of the file with the one last checked in. Admittedly, this is three characters more than your solution, but I think I would like to retain the `-r` argument as a marker that revision control system is used; latexdiff-vc doubles up as a wrapper than can run the required number of (pdf)latex invocations to get pdf/postscript output, which does not necessarily need revision control (currently this second usage implies two non-option arguments, so your solution would also be viable).
