### ISSUE TITLE
Changes of description item parameter is not handled correctly

### ISSUE THREAD

**Issue by andregirard** [ftilmann/latexdiff#161]
A MWE. This is processes with revision 

This is LATEXDIFF 1.2.2a  (Algorithm::Diff 1.1903, Perl v5.22.1)
  (c) 2004-2017 F J Tilmann

new file
```\documentclass{article}
\begin{document}
\begin{description}
\item[D] Item D in the new file
\end{description}
\end{document}
```
old file
```\documentclass{article}
\begin{document}
\begin{description}
\item[C] Item C in the old file
\end{description}
\end{document}
```

yields
[diff.pdf](https://github.com/ftilmann/latexdiff/files/2428441/diff.pdf)

**Comment by ftilmann** [comment]
Fixed in commit a83c418
