### ISSUE TITLE
CULINECHBAR broken for chapter changes

### ISSUE THREAD

**Issue by nioncode** [ftilmann/latexdiff#166]
When I change the title of a chapter, latexdiff will generate a diff.tex like:
```
\chapter{Introduction \DIFdelbegin \DIFdel{of }\DIFdelend \DIFaddbegin \DIFadd{to }\DIFaddend the problem}
```

When using the default mode, everything works fine and the changes are properly marked. However, using `CULINECHBAR`, I get an error: 
```
Package xcolor Error: Undefined color `RED'`
```

By putting
```
\colorlet{BLUE}{blue}
\colorlet{RED}{red}
```
into my preamble, I can work around that. 

When using the default style, latexdiff automatically adds
```
\RequirePackage{color}\definecolor{RED}{rgb}{1,0,0}\definecolor{BLUE}{rgb}{0,0,1}
```
to the preamble of the diff, which seems to be missing for `CULINECHBAR`.

**Comment by ftilmann** [comment]
I have added the upper case definitions into the preamble for CULINECHBAR
Commit e8da103
(This will be in release 1.3.1 or higher). 
If you work from the git version let me know if this fixed the issue
