### ISSUE TITLE
\DIFadd & \DIFdel seem to work within \citep

### ISSUE THREAD

**Issue by slayoo** [ftilmann/latexdiff#17]
Hello,

Trying to troubleshoot overly-long \mboxes introduced by latexdiff when handling changes within optional arguments to natbib's \citep[], I've realised that the mboxes seem not to be needed:

```
\citep[\DIFadd{a}\DIFdel{b}][]{KK07}
```

works fine.

How to force latexdiff to behave like that? (i.e., I guess there's no such option, but perhaps it's doable with a short patch?).

Thanks for help,
Sylwester

**Comment by ftilmann** [comment]
Unfortunately, this is not trivial, as normally only the last argument of a command can be treated as non-atomic text. For now there is only the option to disable markup in citations completely (using --disable-citation-markup option) or choose a different markup style without underlining (e.g. -t CFONT)
I will leave this issue open, as eventually there might be more flexibility in defining text commands, and your use case will actually work. But in any case the \mbox'es would still be needed where the actual reference as changed.
(a 'hacky' way to achieve this would be to preprocess the text such that \citep[arg1][arg2]{ref} is transformed to \CITEPMOD{ref}{arg2}{arg1}, and then define \CITEPMOD as textcmd), then post-process to transform back to initial version (but this will only deal with changes in arg1 not in arg2, so I don't think I will implement it that way - if you know Perl and want to have a go subroutines preprocess and postprocess would need to be modified).

**Comment by slayoo** [comment]
Thanks for help! The "-t CFONT" option solved the issue for me.

**Comment by cmeeren** [comment]
If you want to use latexdiff with strikethrough/underline style and still get nice citation diffs, check out [latexdiffcite](https://latexdiffcite.readthedocs.org). :)

**Comment by ftilmann** [comment]
Sounds interesting.  I will give it a try soon, and adding to the 
README/docs sounds like a good idea (be patient, though).

**Comment by cmeeren** [comment]
:+1:

**Comment by slayoo** [comment]
Two years later I happened to Google my own question :) ... but that's not the point.
@cmeeren Trying out latexdiffcite I have encountered a problem parsing a document containing

```latex
\citep[text text $\dot{T}$][text text]{label}.
```

The parser exits with:

```
Traceback (most recent call last):
  File "/usr/local/bin/latexdiffcite", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/latexdiffcite/latexdiffcite.py", line 163, in main
    run(parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/latexdiffcite/latexdiffcite.py", line 296, in run
    process_revision('old')
  File "/usr/local/lib/python2.7/dist-packages/latexdiffcite/latexdiffcite.py", line 353, in process_revision
    get_capture_groups_from_bbl(oldnew)
  File "/usr/local/lib/python2.7/dist-packages/latexdiffcite/latexdiffcite.py", line 432, in get_capture_groups_from_bbl
    raise ValueError('No match in bbl file for reference ' + ref + ' using regex ' + exp)
ValueError: No match in bbl file for reference T using regex \\bibitem\[{((?:(?!^$).)*?)\(((?:(?!^$).)*?)(?:{\\natexlab{(.?)}})?\)((?:(?!^$).)*?)}\]{T}
```

HTH,
Sylwester

**Comment by cmeeren** [comment]
@slayoo Since this is not related to latexdiff (which I'm not affiliated with in any way) but rather to latexdiffcite, and since it seems to be the same issue as https://github.com/cmeeren/latexdiffcite/issues/2, please post there. And see my most recent comment in that thread - enable debug logging or terminal output and let me know what it says.

**Comment by ftilmann** [comment]
I will close this as @cmeeren correctly points out that this is an issue for latexdiffcite (sorry for not yet following up on my earlier promise to somehow work on integration or at least highlight latexdiffcite in the docs - it's not forgotten, though)

**Comment by slayoo** [comment]
Thanks for your replies!
