### ISSUE TITLE
--flatten does not handle import package commands (\import, \subimport, etc)

### ISSUE THREAD

**Issue by jasonmccsmith** [ftilmann/latexdiff#172]
This one is beyond my capacity to figure out, bumping it up to the issues list.

I've recently encountered a need to use the import package (https://ctan.org/pkg/import) to handle some complicated document structures.  Specifically, I am using the \subimport command:

\subimport{relative_directory}{file}

This sets subsequent uses of \input, \include, etc within _file_ to be calibrated to the _directory_ indicated.

_flatten_ would be the proper place for this, but my perl fu is not up to the task.  Happy to help test.

**Comment by jasonmccsmith** [comment]
As a followup:  I first considered handling this in an external script ala issue #165 / #167 , but latexdiff's native _flatten_ needs to know about the updated relative directories, this probably needs to be handled within _flatten_.

**Comment by jasonmccsmith** [comment]
Pull request for fix.  Perl fu leveled up.

**Comment by ftilmann** [comment]
Pull request was merged - I close this issue but note 'homework' in my comments to PR
