### ISSUE TITLE
latexdiff-vc does not pass options with '.tex' to latexdiff

### ISSUE THREAD

**Issue by nlskrg** [ftilmann/latexdiff#175]
Using the command
``latexdiff-vc --preamble=diffpreamble.tex --git -r XXX -r XXX main.tex``
does not pass the parameter ``--preamble=diffpreamble.tex`` to latexdiff, but considers it an input tex file. Renaming `diffpreamble.tex` to `diffpreamble` is a workaround.

**Comment by ftilmann** [comment]
Should be fixed by commit 58a787e
