### ISSUE TITLE
erroneous diff in presence \href

### ISSUE THREAD

**Issue by sdorof1** [ftilmann/latexdiff#178]
If bbl contains \href, resulting diff is not compiling.

Attached MWE is a git repo. Diff revision branch vs master:

`latexdiff-git --flatten -r master manuscript.tex`

we get `manuscript-diffmaster.tex` which compiles with errors.
Fixed version is also present `manuscript-diffmaster-fixed.tex`

[ladexdiff-issue.zip](https://github.com/ftilmann/latexdiff/files/3635076/ladexdiff-issue.zip)

**Comment by nail1962** [comment]
I have the same problem. I posted above. I see that there is no solution?

**Comment by ftilmann** [comment]
Should be fixed by the commit mentioned above
