### ISSUE TITLE
latexdiff-vc --flatten cannot handle inputs correctly

### ISSUE THREAD

**Issue by fdietze** [ftilmann/latexdiff#18]
It breaks when one revision includes a file which does not exist in the other revision.

**Comment by ftilmann** [comment]
latexdiff-vc does not currently play well with -flatten. For -svn and 
-git flavours at least some improvements are in progress.

**Comment by ftilmann** [comment]
Option --flatten to latexdiff-vc now triggers checkouts of subtrees after commit  c90d672..3fc039e
