### ISSUE TITLE
Support for \sidenote

### ISSUE THREAD

**Issue by nikAizuddin** [ftilmann/latexdiff#192]
Hi, I'm using `\sidenote` from [sidenotes](https://ctan.org/pkg/sidenotes?lang=en) package. It seems `latexdiff` ignore any changes in `\sidenote{}`.

**Comment by ftilmann** [comment]
You can try  `--append-textcmd=sidenote` option.
Let me know if it works, as this option would be easy to add to the defaults

**Comment by nikAizuddin** [comment]
@ftilmann Thank you, it works.

**Comment by ftilmann** [comment]
Ok, I have added this to the defaults, so in the future you won't have to do this in newer version
