### ISSUE TITLE
Unknown regexp modifier "/n"

### ISSUE THREAD

**Issue by rsf83F4qW26jC6MVqBVC** [ftilmann/latexdiff#201]
When calling (via latexdiff-vc) via the command

`latexdiff-vc --math-markup=whole --force --pdf --git --revision TagName DocName.tex`

I get the error

`Unknown regexp modifier "/n" at /Library/TeX/texbin/latexdiff line 1974, near "=~ "`

Running version 1.3.1, as installed by mactex, onto MacOS 10.15.5.

**Comment by ftilmann** [comment]
It is fixed in master. You can fix this in the release by editing line 1974 and changing 
 `m(#[0-9])n`  to `m(#[0-9])` near the end of the line, i.e. remove the trailing n.  Sorry for the inconvenience.

**Comment by rsf83F4qW26jC6MVqBVC** [comment]
You are doing a huge service for the community . . .  Thanks for the fix.  👍
