### ISSUE TITLE
Multi-argument text commands problem

### ISSUE THREAD

**Issue by weirdNox** [ftilmann/latexdiff#206]
Hello!
Following our discussion in #204, here is the problem I was referring to about text commands.
It actually is a bit different of what I described earlier, but I think the behavior is incorrect.

Test files: [textcmd_test.zip](https://github.com/ftilmann/latexdiff/files/4816432/textcmd_test.zip)
Command: `latexdiff --append-textcmd=cmd old.tex new.tex > diff.tex`

After diffing, a text command `\cmd` with two arguments gets separated into two versions (expected), but the first one only has one argument (problem), and the first argument also ends up with `\DIFadd` and `\DIFdel` in both instances (problem, as the manual says only the last argument should be diffed).

**Comment by ftilmann** [comment]
Was a more subtle issue than expected but should be fixed now with 702f570

**Comment by weirdNox** [comment]
Awesome! Thank you :)
