### ISSUE TITLE
bug when change a reference (eqref) example attached

### ISSUE THREAD

**Issue by ouboub** [ftilmann/latexdiff#210]
I run 
latexdiff-so test2-old.tex  test2.tex > diff.tex
the diff file has the old wrong reference commented out
\DIFdelbegin %DIFDELCMD < \eqref{eq:sec3-applications:1} %%%
\DIFdelend \DIFaddbegin \eqref{eq:sec3-applications:15} \DIFaddend with respect to the
I attach the files
regards
Uwe Brauer 
PS, since github does not allow tex files I had to name them txt, sigh
[test2.txt](https://github.com/ftilmann/latexdiff/files/5030149/test2.txt)
[test2-old.txt](https://github.com/ftilmann/latexdiff/files/5030152/test2-old.txt)
[diff.txt](https://github.com/ftilmann/latexdiff/files/5030155/diff.txt)
[diff.pdf](https://github.com/ftilmann/latexdiff/files/5030156/diff.pdf)

**Comment by ftilmann** [comment]
This is expected behaviour, as eqref is a special command added by amsmath package that latexdiff doesn't know about . You get the desired behaviour with the `--append-safecmd=eqref` option.  As amsmath is fairly common, of course, I have just added that to the default list.
