### ISSUE TITLE
latexdiffcite: wrapper around latexdiff to make citations diff properly

### ISSUE THREAD

**Issue by cmeeren** [ftilmann/latexdiff#22]
I am a heavy user of latexdiff. Great tool, thanks! I have always been annoyed that citations do not diff properly. So I set out to fix that, and that resulted in [latexdiffcite](https://latexdiffcite.readthedocs.org), which is a wrapper around latexdiff to make citations diff properly.

This is not a replacement for latexdiff, it's just a wrapper. I think it could be very useful for all who use latexdiff for scientific papers and similar (and those are probably quite a few!). I would be ever so grateful if you could consider spreading the word, maybe mention it in your readme/docs. :smiley:

**Comment by ftilmann** [comment]
Done  with  e3a91c3..8c3ad6f
