### ISSUE TITLE
git-latexdiff has moved, update doc

### ISSUE THREAD

**Issue by pmeckoni** [ftilmann/latexdiff#223]
The web url for git-diff mentioned in the manual does gives an error indicating it is no longer there.
https://github.com/ftilmann/latexdiff/blob/81dedbf8d207836bd19fe2f7fad2a95a3fc13f54/latexdiff-man.tex#L363

The correct url may be here https://gitlab.com/git-latexdiff/git-latexdiff but I have no way of checking if that is the correct url.

Please update the manual when you can.

**Comment by ftilmann** [comment]
Thanks for reporting (and sorry for taking so long to react). I also made links clickable now with hyperref
