### ISSUE TITLE
Github action

### ISSUE THREAD

**Issue by tinosulzer** [ftilmann/latexdiff#226]
Would it be possible to make a github action that automatically runs latexdiff on a specified latex file in the repository whenever a new commit is made, then provides the resulting PDF (e.g. opens a PR adding the PDF to the repository)?

For example, say my working latex file is `main.tex`, whenever I make a commit the github action runs latexdiff on the existing and new version of `main.tex` and opens a PR to add/update the file `main_latexdiff.pdf`

**Comment by ftilmann** [comment]
To be honest, I have no idea, as I am not enough of a github wizz to understand github actions.  I will leave this issue open for others to pick up.

**Comment by tinosulzer** [comment]
https://github.com/priyanshuone6/latexdiff-action
