### ISSUE TITLE
Argument parsing for latexdiff-vc

### ISSUE THREAD

**Issue by masonlr** [ftilmann/latexdiff#24]
Hi, are we supposed to be able to run commands similar to

       latexdiff-vc --git -t CTRADITIONAL -r foo.tex

to get a foo-diff.tex file showing uncommitted changes? I think the [latexdiff-options] component causes problems here. You can test/possibly fix by changing (at https://github.com/ftilmann/latexdiff/blob/master/latexdiff-vc#L128-L132)

      unshift @ARGV,$revs[$#revs];

to 

        push @ARGV,$revs[$#revs];

**Comment by ftilmann** [comment]
Thanks for reporting this and the patch (committed in 078daa9 )
