### ISSUE TITLE
--version and --help should result in exit code 0 (not 1)

### ISSUE THREAD

**Issue by tdegeus** [ftilmann/latexdiff#248]
In preparing https://github.com/conda-forge/staged-recipes/pull/16914 I noticed that update `--help` and `--version` currently `die` is called which results in a command-line error (exit code 1, and not 0 for normal exit), which it shouldn't: the program stops without as expected.

**Comment by ftilmann** [comment]
I have changed this now. Normally I am nervous to change the API in case other workflows depend on behaviour but I guess in this instance it makes sense.
