### ISSUE TITLE
Misplaced alignment tab character &.

### ISSUE THREAD

**Issue by dongli** [ftilmann/latexdiff#26]
The generated differences are:
```
\DIFdel{The volume $V_i$ of parcel $i$ is defined by the first species:
}\begin{eqnarray*}\DIFdel{
 &
      V_i = \frac{m_i^0}{\rho_i^0},
}\end{eqnarray*}
```
BTW, the version of `latexdiff` is:
```
This is LATEXDIFF 1.0.4  (Algorithm::Diff 1.15 so, Perl v5.20.1)
  (c) 2004-2014 F J Tilmann
```

**Comment by ftilmann** [comment]
I cannot reproduce this. I get:
 \DIFdelbegin \DIFdel{The volume $V_i$ of parcel $i$ is defined by the first species:
}\begin{eqnarray*}
 &
      \DIFdel{V_i = \frac{m_i^0}{\rho_i^0},
}\end{eqnarray*}
 %DIFAUXCMD
\DIFdelend
which works fine
Can you provide full MWE (compileable old and new file), also specify version of latexdiff and options used
