### ISSUE TITLE
Add instructions into Readme

### ISSUE THREAD

**Issue by Rhtyme** [ftilmann/latexdiff#274]
Hello,
First of all, thank you for such an amazing tool. It would be perfect if you could just add installation and usage instructions into Readme.

**Comment by alexpghayes** [comment]
I am also struggling to find a link to docs, would appreciate an obvious link in the README as well

**Comment by Arash-Afshar** [comment]
You can find the full manual at https://muug.ca/mirror/ctan/support/latexdiff/doc/latexdiff-man.pdf
I agree that it would be great to add the link to the Readme.
