### ISSUE TITLE
Bug if a new align envoirement starts with & 

### ISSUE THREAD

**Issue by sax76** [ftilmann/latexdiff#29]
We added a new align environment to our paper. The output of diff.tex produce an error when latex is running. I figured out that the problem was that in the output: 
\begin{align}\DIFadd{
  &-(\beta_1-\beta_2) V \approx
  -\frac{(V-V_1)^2}{2 \sigma_1^2} + \frac{(V-V_2)^2}{2 \sigma_2^2}
  \nonumber}\\
  &\DIFadd{\>\>-\beta_1 V_1 + S(V_1,N) + \beta_2 V_2 - S(V_2,N)\>.
}\end{align}
the first tabulator character & must be outside of the \DIFFadd environment. If one replace:
\begin{align}&\DIFadd{
  -(\beta_1-\beta_2) V \approx
  -\frac{(V-V_1)^2}{2 \sigma_1^2} + \frac{(V-V_2)^2}{2 \sigma_2^2}
  \nonumber}\\
  &\DIFadd{\>\>-\beta_1 V_1 + S(V_1,N) + \beta_2 V_2 - S(V_2,N)\>.
}\end{align}
all is fine.

**Comment by ftilmann** [comment]
I cannot reproduce this. When I use align environment, it does exclude the "&" from \DIFadd event at the beginning of the environment.
Can you provide more detail, i.e. MWE (old and new file), version of latexdiff used, and command line.
Does latexdiff know that you are using amsmath macros? If the preamble is included it should pick this up, but if amsmath is included as part of another package and does not appear explicitly, or you are parsing preamble free text, it might be missed. You can tell it explicitly by using option `--packages=amsmath`

**Comment by sax76** [comment]
Thanks for your response.  I have reduced the documents to the relvevant part. Under the links to google drive below (here no files are attachable or?) you find the files oldversion.tex and newversion.tex. On my machine (Ubuntu 14.04) the bug is reproducible. 

The output of latexdiff --version is
This is LATEXDIFF 1.0.2  (Algorithm::Diff 1.15 fast, Perl v5.18.2)
  (c) 2004-2012 F J Tilmann
using --package=amsmath did not make any difference. 

Oldversion:
https://drive.google.com/file/d/0B7BT_71o9qyJLU9pMXYtcjBSNHM/view?usp=sharing
Newversion:
https://drive.google.com/file/d/0B7BT_71o9qyJSmFISEpGNzIzRm8/view?usp=sharing
output off 
$latexdiff oldversion.tex newversion.tex > diff.tex:
https://drive.google.com/file/d/0B7BT_71o9qyJQ1lCcWZPSjU5LUU/view?usp=sharing

**Comment by ftilmann** [comment]
The answer is simple: you have to update to the latest version (latexdiff-1.1.0) from CTAN, or the unstable version on github.  I tested your files and it works properly with 1.1.0 but not 1.0.2.

**Comment by sax76** [comment]
Thanks a lot :-)

2015-08-27 13:43 GMT+02:00 ftilmann <notifications@github.com>:
