### ISSUE TITLE
Wrong version number in latexdiff-vc

### ISSUE THREAD

**Issue by leouieda** [ftilmann/latexdiff#290]
Hi @ftilmann, thank you for this package! It's really useful and I can't imagine writing papers without it.

I noticed that the version number in `latexdiff-vc` is still 1.3.2. Is this correct or should it have been updated? Came across this as I was helping package the program in https://github.com/conda-forge/latexdiff-feedstock/pull/3

I was going to send a PR updating it but I noticed the rest of the code is on 1.3.4a so I don't know if that would be helpful.

**Comment by ftilmann** [comment]
Thanks for the notice. What I have generally been doing is to only bump up version number of auxiliary scripts (latexdiff-vc or latexrevise) if there is an actual change to that script, but then bump it immediately to the overall package version [in theory this could happen also with latexdiff itself trailing behind say latexdiff-vc but in practice, there have always been changes to latexdiff for a new version]. This is partially for convenience, as the version numbers are hard-coded in those scripts, but also for me it would be a bit strange if version 1.3.4, say, were identical to 1.3.2, except for the version number change.  If this approach causes problems downstream in packaging, I could consider changing it but of course not for the past.
