### ISSUE TITLE
Broken commented-out verbatim blocks

### ISSUE THREAD

**Issue by jaybosamiya-ms** [ftilmann/latexdiff#308]
The recent commit 668518af6e745050a4f0764b6204418b78dd714c breaks the following (minimized from much larger files) example:
```tex
% \begin{lstlisting}
% \end{lstlisting}
```

Specifically, `latexdiff x.tex x.tex` produces:
```tex
% \begin{lstlisting}
%DIFVRB %
\end{lstlisting}
```
where it has somehow uncommented out the previously-commented-out `\end{lstlisting}`.

**Comment by ftilmann** [comment]
Sorry about that. As you see a fix has been applied

**Comment by jaybosamiya-ms** [comment]
Thanks for the very quick fix :)
