### ISSUE TITLE
labels defined twice when equation is moved

### ISSUE THREAD

**Issue by mommebu** [ftilmann/latexdiff#31]
When I move a labled equation (using the align environement) I end up with an error as the equation lable is used twice: once inside DIFdel and once inside DIFadd. Easily fixed manually by removing the label in the DIFdel section, but an automatic solution would be nice.

**Comment by ftilmann** [comment]
Unfortunately not quite as easy to fix as I had hoped initially.  A work around is to use --math-markup=fine option (which properly comments out deleted label commands) but this will break for complicated equations.

**Comment by ftilmann** [comment]
Fixed by commit 4017c2a
