### ISSUE TITLE
Control over graphics diff or verbatim diff styles

### ISSUE THREAD

**Issue by nealkruis** [ftilmann/latexdiff#310]
If I use the `--preamble` option to customize my diff style, it appears I only have control over the following commands:

- `\DIFaddtex`
- `\DIFdeltex`
- `\DIFaddbegin`
- `\DIFaddend`
- `\DIFdelbegin`
- `\DIFdelend`
- `\DIFmodbegin`
- `\DIFmodend`
- `\DIFaddtexFL`
- `\DIFdeltexFL`
- `\DIFaddbeginFL`
- `\DIFaddendFL`
- `\DIFdelbeginFL`
- `\DIFdelendFL`

However, I can't seem to modify the styles of:
- `\DIFaddincludegraphics`
- `\DIFdelincludegraphics`
- `\lstdefinelanguage{DIFcode}`

in my preamble, it seems like those lines are generated and appended to the preamble by latexdiff anyway and override any definitions I provide. Is there a way to customize these?

**Comment by nealkruis** [comment]
@ftilmann I think my feature request would be to add options for users to choose the color and style commands for both additions and deletions. Something like:

`latexdiff --add-color=blue --del-color=red --add-style="\uwave" --del-style="\sout"`

These could be applied to normal text, graphics, and listings.

Full control over a custom preamble would also be good.

**Comment by ftilmann** [comment]
latexdiff should now be more 'polite' about respecting definitions of graphics and line markup in the custom preamble. Please have a try.  There are some heuristics in there which I am not a 100% respect your use case. 

The idea to make colors in color-markup styles configurable is reasonable but is a different feature request. Feel free to make a new issue for that.
