### ISSUE TITLE
Verbatim string hashes are not always unique

### ISSUE THREAD

**Issue by therussianjig** [ftilmann/latexdiff#36]
Currently the Verbatim strings are hashed based on the length of the string. This does not always resolve to unique hashes. When the hashes are mapped back to strings at the end of the process, sometimes the strings are improperly decoded. 

I have a quick fix for this based off the 1.10 version which I attached here.
[latexdiff.zip](https://github.com/ftilmann/latexdiff/files/51342/latexdiff.zip)

**Comment by ftilmann** [comment]
Thanks. Implemented by commit 2219f491997d217d69e6d2bd736826f10c3ae9d2
