### ISSUE TITLE
By email: Suggestion for verbatim/lstlisting support

### ISSUE THREAD

**Issue by ftilmann** [ftilmann/latexdiff#38]
Email from J. Protze (28/07/2015 14:30)

Dear Frederik,

we use latexdiff quite a lot and I like the tool. But in computer science we have source code snippets in our latex documents - in either verbatim or lstlisting environment. In the attached "ignore" diff, I added the handling of lstlisting as you do it with verbatim - probably you might integrate this to your code?

But we would also like to highlight diffs in the source code blocks.

With the lstlistings environment it's possible to define the style for a line based on a "comment" symbol. For diffs that might be used by prefixing added lines with '+' and deleted lines with '-' and provide different styles for '+' comments and '-' comments.

I hacked something for the lstlistings environment in the attached "support" diff (I'm not too confident with all the perl magic used in your script).
In the postprocessing, I try to find the occurances where the hash for a code block changed. Then I apply a line-by-line diff on the contents of these code blocks and add "+"/"-" to the changed lines.

Verbatim blocks could be handled similarly, after replacing the verbatim environment by lstlisting.

I'm not sure how to integrate this smoothly into the whole tool workflow, without breaking too much. (Especially how to add only the parts of the preamble as listed below that are not already defined in the document)

By adding the following to the preamble, lstlisting blocks will look like the default verbatim block; the morecomment line sets the style for added/removed lines:

``` latex
\usepackage{listings}
\lstdefinelanguage{codediff}{
  morecomment=[f][\color{red!80!black}]-,         % deleted lines
  morecomment=[f][\color{green!60!black}]+,       % added lines
}
\lstdefinestyle{codediff}{
  belowcaptionskip=.25\baselineskip,
  language=codediff,
  showstringspaces=false,
  basicstyle=\ttfamily,
  columns=fullflexible,
  keepspaces=true,
  float,
  floatplacement=H,
  belowskip=\smallskipamount,
  aboveskip=\smallskipamount,
}
\lstset{style=codediff}
```

Do you think, it would be possible, to integrate this to your tool?

Best
Joachim

latexdiff-add-lstlisting-support.diff

``` diff
diff --git a/latexdiff-1.1.0/latexdiff b/latexdiff-1.1.0/latexdiff
index bb75ce4..e368f3c 100755
--- a/latexdiff-1.1.0/latexdiff
+++ b/latexdiff-1.1.0/latexdiff
@@ -658,6 +658,10 @@ if ( length $oldpreamble && length $newpreamble ) {
     # insert latexdiff commands at the end of preamble (default behaviour)
     push @diffpreamble,$latexdiffpreamble;
   }
+  if ( !defined $packages{"listings"} ) {
+  push @diffpreamble,'\usepackage{listings}','\lstdefinelanguage{diff}{','morecomment=[f][\color{red!80!black}]-,         % deleted lines',
+          'morecomment=[f][\color{green!60!black}]+,','}','\lstdefinestyle{cstyle}{language=diff}','\lstset{style=cstyle}';
+  }
   push @diffpreamble,'\begin{document}';
 }
 elsif ( !length $oldpreamble && !length $newpreamble ) {
@@ -1720,7 +1724,9 @@ sub preprocess {
     s/(?<!\\)\\%/\\PERCENTAGE /g ;  # (?<! is negative lookbehind assertion to prevent \\% from being converted
     s/(?<!\\)\\\$/\\DOLLAR /g ;  # (?<! is negative lookbehind assertion to prevent \\$ from being converted
     s/(\\verb\*?)(\S)(.*?)\2/"${1}{". tohash(\%verbhash,"${2}${3}${2}") ."}"/esg;
+    s/(\\lstinline\*?)(\S)(.*?)\2/"${1}{". tohash(\%verbhash,"${2}${3}${2}") ."}"/esg;
     s/\\begin\{(verbatim\*?)\}(.*?)\\end\{\1\}/"\\${1}{". tohash(\%verbhash,"${2}") . "}"/esg;
+    s/\\begin\{(lstlisting\*?)\}(.*?)\\end\{\1\}/"\\${1}{". tohash(\%verbhash,"${2}") . "}"/esg;
     # Convert _n or _\cmd into \SUBSCRIPTNB{n} or \SUBSCRIPTNB{\cmd} and _{nnn} into \SUBSCRIPT{nn}
     1 while s/(?<!\\)_([^{\\]|\\\w+)/\\SUBSCRIPTNB{$1}/g ;
     1 while s/(?<!\\)_{($pat6)}/\\SUBSCRIPT{$1}/g ;
@@ -2038,8 +2044,12 @@ sub postprocess {

     # Expand hashes of verb and verbatim environments (note negative look behind assertion to not leak out of DIFDELCMD comments
     s/(\\verb\*?)\{([-\d]*?)\}/"${1}". fromhash(\%verbhash,$2)/esg;
+    s/(\\lstinline\*?)\{([-\d]*?)\}/"${1}". fromhash(\%verbhash,$2)/esg;
     s/${DELCMDOPEN}\\(verbatim\*?)\{([-\d]*?)\}/"${DELCMDOPEN}\\begin{${1}}".fromhash(\%verbhash,$2,$DELCMDOPEN)."${DELCMDOPEN}\\end{${1}}"/esg;
+    s/\\DIFdelbegin ${DELCMDOPEN}\\(lstlisting\*?)\{([-\d]*?)\}\s*${DELCMDOPEN}\s*${DELCMDCLOSE}\s*\\DIFdelend\s*\\DIFaddbegin\s*\\\1\{([-\d]*?)\}\s*\\DIFaddend/"\\begin{${1}}".join("\n",codediff(fromhash(\%verbhash,$2),fromhash(\%verbhash,$3)))."\\end{${1}}"/esg;
+    s/${DELCMDOPEN}\\(lstlisting\*?)\{([-\d]*?)\}/"${DELCMDOPEN}\\begin{${1}}".fromhash(\%verbhash,$2,$DELCMDOPEN)."${DELCMDOPEN}\\end{${1}}"/esg;
     s/\\(verbatim\*?)\{([-\d]*?)\}/"\\begin{${1}}".fromhash(\%verbhash,$2)."\\end{${1}}"/esg;
+    s/\\(lstlisting\*?)\{([-\d]*?)\}/"\\begin{${1}}".fromhash(\%verbhash,$2)."\\end{${1}}"/esg;
     # Convert '\PERCENTAGE ' back into '\%' (the final question mark catches a special situation where due to a latter pre-processing step the ' ' becomes separated          
     s/\\PERCENTAGE ?/\\%/g;
     # Convert '\DOLLAR ' back into '\$'                   
@@ -2262,6 +2272,29 @@ sub linediff {
   return wantarray ? @$retseq : $retseq ;
 }

+# @diffs=codediff(\@seq1, \@seq2)
+# mark up lines like this
+# - old deleted line(s)
+# + new inserted line(s)
+#   common line(s)
+# Future extension: mark change explicitly
+sub codediff {
+  my $seq1 = shift ;
+  my @seq1 = split /\n/, $seq1;
+  my $seq2 = shift ;
+  my @seq2 = split /\n/, $seq2;
+
+  my $diff = Algorithm::Diff->new( \@seq1, \@seq2 );
+  my $retseq = [];
+
+  while(  $diff->Next()  ) {
+      push @$retseq, $diff->Same();
+      next   if  $diff->Same();
+      push @$retseq, "- $_"   for  $diff->Items(1);
+      push @$retseq, "+ $_"   for  $diff->Items(2);
+  }
+  return wantarray ? @$retseq : $retseq ;
+}


 # init_regex_arr_data(\@array,"TOKEN INIT")


latexdiff-add-lstlisting-ignore.diff

diff --git a/latexdiff-1.1.0/latexdiff b/latexdiff-1.1.0/latexdiff
index bb75ce4..6b9df75 100755
--- a/latexdiff-1.1.0/latexdiff
+++ b/latexdiff-1.1.0/latexdiff
@@ -1720,7 +1720,9 @@ sub preprocess {
     s/(?<!\\)\\%/\\PERCENTAGE /g ;  # (?<! is negative lookbehind assertion to prevent \\% from being converted
     s/(?<!\\)\\\$/\\DOLLAR /g ;  # (?<! is negative lookbehind assertion to prevent \\$ from being converted
     s/(\\verb\*?)(\S)(.*?)\2/"${1}{". tohash(\%verbhash,"${2}${3}${2}") ."}"/esg;
+    s/(\\lstinline\*?)(\S)(.*?)\2/"${1}{". tohash(\%verbhash,"${2}${3}${2}") ."}"/esg;
     s/\\begin\{(verbatim\*?)\}(.*?)\\end\{\1\}/"\\${1}{". tohash(\%verbhash,"${2}") . "}"/esg;
+    s/\\begin\{(lstlisting\*?)\}(.*?)\\end\{\1\}/"\\${1}{". tohash(\%verbhash,"${2}") . "}"/esg;
     # Convert _n or _\cmd into \SUBSCRIPTNB{n} or \SUBSCRIPTNB{\cmd} and _{nnn} into \SUBSCRIPT{nn}
     1 while s/(?<!\\)_([^{\\]|\\\w+)/\\SUBSCRIPTNB{$1}/g ;
     1 while s/(?<!\\)_{($pat6)}/\\SUBSCRIPT{$1}/g ;
@@ -2038,8 +2040,11 @@ sub postprocess {

     # Expand hashes of verb and verbatim environments (note negative look behind assertion to not leak out of DIFDELCMD comments
     s/(\\verb\*?)\{([-\d]*?)\}/"${1}". fromhash(\%verbhash,$2)/esg;
+    s/(\\lstinline\*?)\{([-\d]*?)\}/"${1}". fromhash(\%verbhash,$2)/esg;
     s/${DELCMDOPEN}\\(verbatim\*?)\{([-\d]*?)\}/"${DELCMDOPEN}\\begin{${1}}".fromhash(\%verbhash,$2,$DELCMDOPEN)."${DELCMDOPEN}\\end{${1}}"/esg;
+    s/${DELCMDOPEN}\\(lstlisting\*?)\{([-\d]*?)\}/"${DELCMDOPEN}\\begin{${1}}".fromhash(\%verbhash,$2,$DELCMDOPEN)."${DELCMDOPEN}\\end{${1}}"/esg;
     s/\\(verbatim\*?)\{([-\d]*?)\}/"\\begin{${1}}".fromhash(\%verbhash,$2)."\\end{${1}}"/esg;
+    s/\\(lstlisting\*?)\{([-\d]*?)\}/"\\begin{${1}}".fromhash(\%verbhash,$2)."\\end{${1}}"/esg;
     # Convert '\PERCENTAGE ' back into '\%' (the final question mark catches a special situation where due to a latter pre-processing step the ' ' becomes separated          
     s/\\PERCENTAGE ?/\\%/g;
     # Convert '\DOLLAR ' back into '\$'                   
```

**Comment by mzwiessele** [comment]
+1

**Comment by ftilmann** [comment]
The part adding awareness of lstlisting and lstinline  has been added in commit 9feb46f .
I took the idea from  latexdiff-add-lstlisting-ignore.diff  but made it more flexible by introducing a configuration variable VERBATIMENV.
The codediff add-on is still outstanding so issue remains open.

**Comment by jprotze** [comment]
I'm updating my fixes to the HEAD version. 
Is it ok, to replace all verbatim by a new defined lst-environment?
```
\lstnewenvironment{lstverbatim}{\lstset{style=codediff}}{}
```

**Comment by ftilmann** [comment]
Not yet having actually implemented your fixes but having looked at the code, I think a limitation is that it might have a hard time matching the correct verbatim environments, if there are even minor changes directly before or after the verbatim environment. Even though there might be a work around, I think it might get messy quickly.  So I am thinking of changing the whole way of dealing with verbatim environments and turning them into a special type of comment rather than hiding the content behind the hash. In this way, the line-wise differencing of lines is already built into latexdiff, and post-processing would then just have to turn those special verbatim comments back into the appropriate verbatim environment.  It will possibly be a few weeks until I get around to actually do that, but I wanted you to be aware of this before investing too much time implementing a solution in the current paradigm.

**Comment by ftilmann** [comment]
And to answer your question: I try to generate the diff file in such a way, that the 'new' tex-file can in principle be recovered from the diff file byte-for-byte. So if the verbatim environments are replaced, the original environment should be retained somehow at least in a comment (I currently have no defined way of doing this, but there are probably other use cases). 
I am not sure what should be the expected behaviour for lstlisting.  Using the codediff style the language-specific markup would be lost. Would it be acceptable to lose that in the whole diff document in order to be able to highlight the code changes. Or should it be lost only in those lstlisting environments in which something did actually change (which would of course add to complexity of latexdiff code)?   In my own papers I rarely if ever cite code, so would be interested in your view, what would be the behaviour of least surprise.

**Comment by jprotze** [comment]
For documents that use latexdiff on a regular basis, I personally would prefer to include the style definitions for the diff in the listings environment of the document. This would provide the best result for the diffed pdf. So. probably use a list of environments, that should be replaced (VERBATIMENV) and another list of environments, that handle the necessary diff style in the document.

If you replace verbatim by DIFverbatim, it is easy to revert and restore the original code, actually you could prefix all environments in VERBATIMENV with DIF and define a new lstenvironment for them.

In one project, we use a command like `\ID{my_id}` to format variable names special. If used inline in text, it's a redefinition of lstinline to avoid escape sequences in code and apply the formating. If used in a listing environment, we use `\ID{` and `}` as a `moredelim` and apply the formating.
The moredelim scopes can be nested, so I currently use these delimiters for the diff:
```
  moredelim=*[is][\color{red}\sout]{*!----}{----!*},
  moredelim=*[is][\color{blue}\uwave]{*!++++}{++++!*},
```
I thought about using `{\\DIFadd\{}{\}}`, but I found, that the closing } can interfer with closing brackets in the code. The opening and closing delimiter need to be something, that is not present in the code. So, probably these delimiters should also be configurable.

The moredelim approach is also useful for the inlined code variants like verb and lstinline. With lstinline I found two issues in current regexp:
-  lstinline allows also {} as code delimiters. The current regexp looks for the next { to end the listing
-  I'm not sure about tex syntax rules. Is it legal to define a macro that is also a prefix of another macro. Like `\def\foo{\lstinline[style=foo]}` and `\def\foobar{\lstinline[style=foobar]}` ? If that is valid tex, we have a problem with current regexp and probably should probably use something like [^\s\w] for the delimiter.

I hope this makes sense to you.

**Comment by ftilmann** [comment]
> lstinline allows also {} as code delimiters. The current regexp looks for the next { to end the listing

OK, I was not aware of this. As far as I understand the docs, for \verb it is possible to say `\verb{quoted tex{`  ie there is nothing special about braces. Also, optional arguments of lstinline are currently not accounted for. So in the end this needs a dedicated regex, as the behaviour is different to \verb, but it is easy to do in principle.  My reply to the next point assumes that this has already been implemented, i.e. that optional arguments to lstinline are accounted for. 

> I'm not sure about tex syntax rules. Is it legal to define a macro that is also a prefix of another macro. Like \def\foo{\lstinline[style=foo]} and \def\foobar{\lstinline[style=foobar]} ? If that is valid tex, we have a problem with current regexp and probably should probably use something like [^\s\w] for the delimiter.

I have no idea whether this would be legal or not, but it should be easy enough to just try out. The general philosopy of latexdiff has been not to even try to to deal with raw TeX commands like \def as this is much harder to do. However, normally, this would not matter if there was no change in these TeX commands. In your example, really the whole processing is mixed up. Mitigating this is that \def commands are usually given in the preamble which is processed in line mode, so this would not be an issue there.  And if you absolutely must use such a command in the body, the following work around might work:
```
\def\foo{\lstinline[style=foo]% %
}
```
(would need to be used in both old and new document). Now this would rely on TeX to strip out the comments before processing the \def.

**Comment by ftilmann** [comment]
Regarding your suggestion with DIFverbatim (and friends) and moredelim.  This sounds interesting but I am not really familiar with the listings package, so cannot fully follow the details. Could you construct and post an MWE of how you think the diff file should look in the end (no need to have a real new and old file, just a fake diff file would be fine, which is complete in the sense that I can compile it, and where at least one line in a code example is changed so that I can see how exactly you would combine the highlighting with existing code markup, and what output you would expect latexdiff to generate.

**Comment by jprotze** [comment]
This MWE includes diff for `\verbatim`, a selfdefined lst environment and inline `\verb`

```
\documentclass{article}
\usepackage{listings}
\usepackage{xcolor}
\usepackage{ulem}

\lstdefinelanguage{codediff}{
%  moredelim=*[is][\color{red}\sout]{*!----}{----!*},
%  moredelim=*[is][\color{blue}\uwave]{*!++++}{++++!*},
  moredelim=**[is][\color{red!80!black}]{*!----}{----!*},
  moredelim=**[is][\color{green!60!black}]{*!++++}{++++!*}
}
\lstdefinestyle{codediff}{
	belowcaptionskip=.25\baselineskip,
	language=codediff,
%    showspaces=true,
	basicstyle=\ttfamily,
	columns=fullflexible,
	keepspaces=true,
	moredelim=**[is][\rmfamily\mdseries\itshape]{\\ID\{}{\}},
}
\lstnewenvironment{DIFverbatim}{\lstset{style=codediff}}{}
\def\DIFverb{\lstinline[style=codediff]}
\lstnewenvironment{MYcode}{\lstset{style=codediff}}{}

\begin{document}

\section{verbatim}

OLD:
\begin{verbatim}
int main(){return 0;}
\end{verbatim}

\noindent NEW:
\begin{verbatim}
int main(int argc, char** argv){
  printf("Hallo Welt!\n");
  return 0;
}
\end{verbatim}

\noindent Possible diff (changing lines):
\begin{DIFverbatim}
*!----int main(){return 0;}----!*
*!++++int main(int argc, char** argv){++++!*
*!++++  printf("Hallo Welt!\n");++++!*
*!++++  return 0;++++!*
*!++++}++++!*
\end{DIFverbatim}

\noindent Minimal diff:
\begin{DIFverbatim}
int main(*!++++int argc, char** argv++++!*){*!++++
  printf("Hallo Welt!\n");
  ++++!*return 0;*!++++
++++!*}
\end{DIFverbatim}

\section{lstlisting}

\noindent OLD (lstlisting environment MYcode):
\begin{MYcode}
int main(){return 0;}
\end{MYcode}

\noindent NEW (lstlisting environment MYcode):
\begin{MYcode}
int main(int \ID{argc}, char** \ID{argv}){
  printf("Hallo Welt!\n");
  return 0;
}
\end{MYcode}

\noindent Diff for MYcode environment:
\begin{MYcode}
int main(*!++++int \ID{argc}, char** \ID{argv}++++!*){*!++++
  printf("Hallo Welt!\n");
  ++++!*return 0;*!++++
++++!*}
\end{MYcode}

\section{inline verb}

\noindent OLD: inline verbatim: $\rightarrow$\verb|#define some_type int|$\leftarrow$

\noindent NEW: inline verbatim: $\rightarrow$\verb|typedef int some_type;|$\leftarrow$

\noindent DIFF: inline verbatim: $\rightarrow$\DIFverb|*!----#define some_type----!**!++++typedef++++!* int*!++++ some_type;++++!*|$\leftarrow$ 

\end{document}
```

I'm not sure wether the minimal, compact version of the listing diff is the preferred one. Really fancy would be a result that looks like the diff you get from github, where you have a line-by-line diff, that highlights the actual changes in the line.

The asterisks in `moredelim=**` modify the transitivity of the applied font modifications. With **, the modification is also applied to the `\ID{}`region. But with **, `\sout` and `\uwave` don't show any effect (I don't know why), while they do with the single *.

**Comment by ftilmann** [comment]
All variants of `lstinline` should now be processed correctly, and `\verb` and `\lstline` commands are now shown in the appropriate colour (red or blue) for coloured styles. In the end I did not use the definition of codediff because in the way solved it now does not create additional dependency on listings package, and it will preserve all other attributes of the lstinline style. 

I know that the processing of longer verbatim and listing environments is more important than this but thought I would try out the approach with this one. Multiline diff's are still on the agenda (probably then using the codediff style, though I have not completely made up my midn on that one) but I have no immediate plans to tackle the minimal diff or github style.
 The minimal diff essentially requires a word-wise diff which will require some knowledge of the language shown I think, which is not really feasible. The github style diff would be nice, but I would need to implement the algorithm for that inside latexdiff, and this is just too much work.  For most use cases the line-wise diff will be sufficient in any case I think.  Of course, if anyone else wants to do this, I am happy to consider pull requestes :-)

**Comment by ftilmann** [comment]
@jprotze   I just uploaded commit  b02a1b6  which achieves the line-by-line verbatim markup using the listings package. I don't have too many examples to try this out with, so if you are still watching this thread, I would appreciate if you could try it out on some of your documents, as they are potentially many special cases. In any case thanks for your help with giving me the first idea how to approach this and your other examples.
