### ISSUE TITLE
$ round minipage that includes $ causes confusion

### ISSUE THREAD

**Issue by RBornat** [ftilmann/latexdiff#39]
I have a minipage which I must wrap with $..$, to allow a brace. Inside is some math text which I must wrap with $. Latexdiff thinks the first $ matches with the first $ of the internal math, and the second $ of the internal text with the final $. I can't see in the documentation any way to solve the problem.

original.txt is the original; modification.txt has some changes; diff.txt is what latexdiff makes of it.

[diff.txt](https://github.com/ftilmann/latexdiff/files/87447/diff.txt)

[modification.txt](https://github.com/ftilmann/latexdiff/files/87448/modification.txt)
[original.txt](https://github.com/ftilmann/latexdiff/files/87449/original.txt)

**Comment by ftilmann** [comment]
This represents a real edge case. This will be quite tricky to fix. I can only suggest to replace one (but not both)  of the $..$ pairs with \( .. \) to help latexdiff to make the correct match. Of course this would need to be done in the old and new text document.

**Comment by RBornat** [comment]
I can find a workaround. I can see that this would be very difficult to fix. So please close the issue. (Sorry, I'm new to intensive use of latexdiff. Once I got it to work -- my use of equation stuff is a bit difficult to deal with, so I had to use '--math-markup="off"' -- I'm very happy.
