### ISSUE TITLE
pdf output with Lua(La)TeX

### ISSUE THREAD

**Issue by surmann** [ftilmann/latexdiff#40]
I would suggest to extent the option `--pdf` to an option in which one can set the latex version to use, `lualatex` in my case.

To be consequent, we should add an option to set the bibliography, index, and glossary tool. Probably, these are options to set in the preamble file, than in the command line.

**Comment by ftilmann** [comment]
This was a good suggestion. All the processing commands are configurable now. To use lualatex you would use the options (for latexdiff-vc)
"--pdf --config LATEX=lualatex"
(Fixed in 42f1034, release versions 1.2.1 upward)
