### ISSUE TITLE
strange effect of commented command

### ISSUE THREAD

**Issue by RBornat** [ftilmann/latexdiff#41]
I have some texts which aren't different, but which contain a commented command. With the commented command present, I get strange results (which don't compile). Without it, no problem.

One text in original2.txt, the other in modification2.txt (they are identical) and the result in diff2.txt.

[diff2.txt](https://github.com/ftilmann/latexdiff/files/90453/diff2.txt)
[modification2.txt](https://github.com/ftilmann/latexdiff/files/90455/modification2.txt)
[original2.txt](https://github.com/ftilmann/latexdiff/files/90454/original2.txt)

**Comment by ftilmann** [comment]
I am sorry: I cannot reproduce this. 
For me
     `latexdiff original2.txt modification2.txt > diff2.txt`
results in diff2.txt being identical to the other two files.  Which version of latexdiff are you using (though this should work in any version). Are you on Windows, Mac or Linux  (could matter because of line endings)

**Comment by RBornat** [comment]
I'm now running 1.1.1-fast on a Mac

This is LATEXDIFF 1.1.1  (Algorithm::Diff 1.15 fast, Perl v5.18.2)
  (c) 2004-2015 F J Tilmann

and it does the same for me: no inserts in the diff file. It was an excerpt from a much larger diff, and I thought I had taken enough context. And it may have been from before I was running 1.1.1. I'm sure it must have been, because now when I re-insert the commented lines I get valid Latex code. Whoops.

So please close this one too. Oh dear, I'm not doing very well in submitting latexdiff bugs. Thanks again, and I'll go quiet.

**Comment by ftilmann** [comment]
No worries, glad to hear it's working for you, too, now
