### ISSUE TITLE
support of git tags

### ISSUE THREAD

**Issue by surmann** [ftilmann/latexdiff#42]
What do you think in adding the possibility to access tags in addition to commit revisions?
I tag a commit when I send a document to revision. After several commits a create a new pdf for revision. Currently, I have to lookup the correct commit with respect to the last tag.

Thanks!

**Comment by ftilmann** [comment]
I don't really understand what you are talking about.  Do you mean the way latexdiff-vc --git behaves. Can you just show me the example command and what is actual and desired behaviour
(note that I will be away on business trip for next 2 weeks, so please be patient with any further reply)

**Comment by surmann** [comment]
Currently, it is possible to do a diff versus a specific commit (here `abcdef`):
`latexdiff-vc --git -r abcdef file.tex`
I would like to do something similar with a tag (here `v2.3`):
`latexdiff-vc --git --tag v2.3 file.tex`

Is my suggestion now a bit more understandable?

**Comment by gaulinmp** [comment]
It works for me, `-r` seems to figure out it's a tag: `latexdiff-vc --git -r v1.0 file.tex`

**Comment by ftilmann** [comment]
Interesting.  Maybe this has only been implemented in recent versions of git? @gaulinmp, could you post the version of git you are using. 
If @surmann is still following this, can you check whether this works for you, too?

**Comment by surmann** [comment]
@ftilmann Yes, this works for me. Thanks!

**Comment by gaulinmp** [comment]
My versions:

    git version 2.7.4
    hub version 2.2.1

**Comment by ftilmann** [comment]
Great. A bug that fixed itself so to say - I will close this then
