### ISSUE TITLE
latexdiff incompatible with matched half brackets, e.g., \left(\right.

### ISSUE THREAD

**Issue by cairunze** [ftilmann/latexdiff#45]
difficulty encountered using latexdiff when the tex file contains matched half brackets like \left(\right. or \left.\right)

The details are in 
http://tex.stackexchange.com/questions/290911/latexdiff-incompatible-with-half-brackets/290914#290914

It is suggested that this is a bug and should be reported. 
Many thanks!

**Comment by ftilmann** [comment]
That link did not work for me. The solution is already given by Andrew Swann in the answer, and I will upload this in the next few days when I got around to testing another unrelated change

http://tex.stackexchange.com/questions/290911/latexdiff-incompatible-with-half-brackets
