### ISSUE TITLE
Error on Windows - exit code 255

### ISSUE THREAD

**Issue by nickerx** [ftilmann/latexdiff#48]
Hi,
I just started using latexdiff and I tried to run `latexdiff -h` and `latexdiff --version` on a normal Windows 10 console and in both cases the output looks fine but then ended
* for `-h` with
```
C:\texlive\2015\bin\win32\runscript.tlu:665: command failed with exit code 255:
perl.exe c:\texlive\2015\texmf-dist\scripts\latexdiff\latexdiff.pl -h
```
 * for `--version` with 
```
C:\texlive\2015\bin\win32\runscript.tlu:665: command failed with exit code 255:
perl.exe c:\texlive\2015\texmf-dist\scripts\latexdiff\latexdiff.pl --version
```
It looks likes its the same output, it just differ for the call to `latexdiff.pl`, is this output a normal behavior?
As you can tell from the directories I've TeXLive 2015 and `--version` says I've latexdiff version 1.1.1.

**Comment by ftilmann** [comment]
No, of course it's not normal behaviour, but the problem is not with latexdiff, but there is something wrong with your installation (have you checked whether perl.exe installed?).  I am afraid I can't help you there - maybe you can take this up with texlive maintainers?
