### ISSUE TITLE
A new markup option: pdflatex + pdfcomment

### ISSUE THREAD

**Issue by peci1** [ftilmann/latexdiff#49]
I managed to get a version of the diff that marks the changes utilizing the `pdfcomment` package. It is actually quite useful, since the compiled diff should be rendered exactly the same as the current version of the document.

Here's what's needed (I'm no LaTeX hacker, so maybe there are some `protect`s or other stuff to be added):

    \usepackage[author={anonymous}]{pdfcomment}
    \providecommand{\DIFaddtex}[1]{\pdfmarkupcomment[markup=Underline]{#1}\space{}}
    \providecommand{\DIFdeltex}[1]{ \pdfcomment[icon=Insert]{#1}}

**Comment by ftilmann** [comment]
Sounds like an interesting idea.  I will try it out, and if it works well, add it as a style choice

**Comment by ftilmann** [comment]
I largely implemented your suggestion but modified the option to commands a bit. In particular I was concerned that the 'delete' symbols cover up the text, and added some horizontal space to avoid that. This means that the layout is not exactly the same but it should be pretty close and I think it's a price worth paying for avoiding overlap.  
Commit: fc387f3 ...

**Comment by peci1** [comment]
Nice, thanks!

**Comment by faroit** [comment]
@ftilmann I wonder if its possible to actually make `PDFCOMMENT` optional. That means we have the usual inline changes but additionally add pdf comments. That way, users that use supported PDF readers will be able to quickly navigate to the modified changes by browsing the list of pdf comments.  Does this make sense?
