### ISSUE TITLE
! Paragraph ended before \UL@word was complete.

### ISSUE THREAD

**Issue by roberthannah89** [ftilmann/latexdiff#51]
When you create a diff (I'm using Cygwin on Windows 10) I frequently get this error:

> Paragraph ended before \UL@word was complete.

This error is produced by such lines as:

```

\DIFdelbegin \DIFdel{A thorough reading of this section is essential.
(NEW LINE)
}\DIFdelend 
```

Apologies: How do you do a new line in GitHub?

Removing the newlines between the end of the bracketted text and the "}" resolved the problem

`\DIFdelbegin \DIFdel{A thorough reading of this section is essential.}\DIFdelend`

But this error can occurs dozens of times in the same document!

**Comment by ftilmann** [comment]
Although I can say for sure, this type of error often occurs when mixing Unix and DOS line ends. Try applying unix2dox or dos2unix to both input files.  If this does not fix it, post a minimum working (failing) example

**Comment by roberthannah89** [comment]
Running dos2unix on both files appears to fix this issue.

Other people appear to have had this issue in a different context: http://tex.stackexchange.com/questions/5055/latexdiff-error-caused-by-multi-paragraph-sout-paragraph-ended-before-ulon

I don't suppose there is any way make this occur automatically?

**Comment by ftilmann** [comment]
It's supposed to do this already on linux. Could you send me the files in question by some way preserving line endings (i.e. not copy/pasting here), e.g. as email attachment, and let me know on which operating system you are (`perl -e 'print $^O \n'`) and which version you are using (output of latexdiff --version).

**Comment by ftilmann** [comment]
Without further input not clear how to continue. I will close this
