### ISSUE TITLE
Changelog should also contain release date of versions

### ISSUE THREAD

**Issue by fkbreitl** [ftilmann/latexdiff#59]
The changelog provided in latexdiff looks informative and concise, but one missing item is the release date.
It would be nice if this could be added for future versions and maybe even reconstructed for the past.

**Comment by ftilmann** [comment]
WIth the latest release (1.2.1) I have followed your suggestion (changelog provided by comments in the source code). I will not do this for the past because I don't think it's worth the effort but I attach a listing of file time stamps for all the  releases under github:
```
-rw-r--r-- 1 tilmann tilmann 436946 Jul 21  2014 latexdiff-1.0.4.tar.gz
-rw-r--r-- 1 tilmann tilmann 458723 Apr 14  2015 latexdiff-1.1.0.tar.gz
-rw-r--r-- 1 tilmann tilmann 467096 Dec 26  2015 latexdiff-1.1.1.tar.gz
-rw-r--r-- 1 tilmann tilmann 474116 Aug 15  2016 latexdiff-1.2.0.tar.gz
-rw-r--r-- 1 tilmann tilmann 491580 Jun 22 10:26 latexdiff-1.2.1a.tar.gz
-rw-r--r-- 1 tilmann tilmann 491542 Jun 22 10:45 latexdiff-1.2.1.tar.gz
```

**Comment by fkbreitl** [comment]
Great! Thank you!
