### ISSUE TITLE
README mentions obsolete "latexdiff-so"

### ISSUE THREAD

**Issue by cmarqu** [ftilmann/latexdiff#63]
The README file mentions the command ``latexdiff-so`` which I assume has become just ``latexdiff``?

**Comment by ftilmann** [comment]
No, in the release tar-ball or the equivalent reference release on CTAN the latexdiff-so file still exists; it is generated automatically from the files `latexdiff`  and `Algorithm-Diff-Block` so does not appear in the github repository. Some distributions then rename latexdiff-so or latexdiff-fast to latexdiff, but this is beyond my control.
