### ISSUE TITLE
--math-markup=3  cannot deal with change of environment

### ISSUE THREAD

**Issue by ouboub** [ftilmann/latexdiff#69]
Hello 
please consider the following minimal example.

\documentclass[12pt]{article}
\usepackage{amssymb,amsfonts,amsmath,amsthm}
\begin{document}
\begin{equation*}
\label{eq:compat:3}
 \Phi:A \times B^3 \to C
\end{equation*} 
and our main task in this section is to show that the inverse map exists.
\end{document}

and 

\documentclass[12pt]{article}
\usepackage{amssymb,amsfonts,amsmath,amsthm}
\begin{document}
\begin{displaymath}
\label{eq:compat:3}
 \Phi:A \times B^3 \to C
\end{displaymath} 
and our main task in this section is to show that the inverse map exists.
\end{document}
using latexdiff 1.2.0
the command 
latexdiff --math-markup=3 test2.tex test2-old.tex > diff.tex
generates the following diff file
\documentclass[12pt]{article}
%DIF LATEXDIFF DIFFERENCE FILE
%DIF DEL test2.tex       Mon Nov 28 16:12:30 2016
%DIF ADD test2-old.tex   Mon Nov 28 16:12:09 2016
\usepackage{amssymb,amsfonts,amsmath,amsthm}
%DIF PREAMBLE EXTENSION ADDED BY LATEXDIFF
%DIF UNDERLINE PREAMBLE %DIF PREAMBLE
\RequirePackage[normalem]{ulem} %DIF PREAMBLE
\RequirePackage{color}\definecolor{RED}{rgb}{1,0,0}\definecolor{BLUE}{rgb}{0,0,1} %DIF PREAMBLE
\providecommand{\DIFadd}[1]{{\protect\color{blue}\uwave{#1}}} %DIF PREAMBLE
\providecommand{\DIFdel}[1]{{\protect\color{red}\sout{#1}}}                      %DIF PREAMBLE
%DIF SAFE PREAMBLE %DIF PREAMBLE
\providecommand{\DIFaddbegin}{} %DIF PREAMBLE
\providecommand{\DIFaddend}{} %DIF PREAMBLE
\providecommand{\DIFdelbegin}{} %DIF PREAMBLE
\providecommand{\DIFdelend}{} %DIF PREAMBLE
%DIF FLOATSAFE PREAMBLE %DIF PREAMBLE
\providecommand{\DIFaddFL}[1]{\DIFadd{#1}} %DIF PREAMBLE
\providecommand{\DIFdelFL}[1]{\DIFdel{#1}} %DIF PREAMBLE
\providecommand{\DIFaddbeginFL}{} %DIF PREAMBLE
\providecommand{\DIFaddendFL}{} %DIF PREAMBLE
\providecommand{\DIFdelbeginFL}{} %DIF PREAMBLE
\providecommand{\DIFdelendFL}{} %DIF PREAMBLE
%DIF END PREAMBLE EXTENSION ADDED BY LATEXDIFF

\begin{document}
\DIFdelbegin %DIFDELCMD < \begin{equation*}
%DIFDELCMD < %%%
\DIFdelend \DIFaddbegin \begin{displaymath}
\DIFaddend \label{eq:compat:3}
 \Phi:A \times B^3 \to C
\DIFdelbegin %DIFDELCMD < \end{equation*} 
\end{MATHMODE}%DIFAUXCMD
%DIFDELCMD < %%%
\begin{displaymath}%DIFAUXCMD
\DIFdelend \DIFaddbegin \end{displaymath} 
\DIFaddend and our main task in this section is to show that the inverse map exists.
\end{document}

which cannot be compiled

Uwe Brauer

**Comment by ftilmann** [comment]
Thanks for the report. Does it work with --math-markup=2?  For sure, the processing is not right, the \end{MATHMOD} should have been converted to \end{displaymath} but the FINE (3) math-markup level is not really made where the equation style changes (the change here).

**Comment by ouboub** [comment]
yes it works nicely with  --math-markup=2, which seems to be the safer option, but as I indicate in another issue, there are situations where even  --math-markup=2 fails

**Comment by ftilmann** [comment]
I have seen the other report, and I will look into these other issues, but because of work commitments it might take a few weeks.

**Comment by ouboub** [comment]
Any news on the subject?

**Comment by ftilmann** [comment]
I realise I made a mistake talking about "few weeks". A "few months" would have been more honest. Truth of the matter is there are a number of pending issues, and though I continue to work on latexdiff, the amount of time I can give to this project is quite limited. Of course, pull requests are always welcome. I will close this issue (as it is solved by using --math-markup=2), but will provide a short reply to your other issue just now.
