### ISSUE TITLE
Incompilable diff when using \glqq

### ISSUE THREAD

**Issue by felixinc** [ftilmann/latexdiff#81]
Having two tex-files and using latexdiff can produce uncompilable diff-file. Here is a minimal example

Old version
```tex
\documentclass{amsart}
\usepackage{ngerman}
\usepackage[utf8]{inputenc} 
\begin{document}
X
\end{document}
```
New version
```tex
\documentclass{amsart}
\usepackage{ngerman}
\usepackage[utf8]{inputenc} 
\begin{document}
Yyyy „Yyyy“ Yyyy X
\end{document}
```
Resulting in this incompilable diff-file
```tex
\documentclass{amsart}
\usepackage{ngerman}
\usepackage[utf8]{inputenc} 
\RequirePackage[normalem]{ulem} %DIF PREAMBLE
\RequirePackage{color}\definecolor{RED}{rgb}{1,0,0}\definecolor{BLUE}{rgb}{0,0,1} %DIF PREAMBLE
\providecommand{\DIFadd}[1]{{\protect\color{blue}\uwave{#1}}} %DIF PREAMBLE
\providecommand{\DIFdel}[1]{{\protect\color{red}\sout{#1}}}                      %DIF PREAMBLE
\providecommand{\DIFaddbegin}{} %DIF PREAMBLE
\providecommand{\DIFaddend}{} %DIF PREAMBLE
\providecommand{\DIFdelbegin}{} %DIF PREAMBLE
\providecommand{\DIFdelend}{} %DIF PREAMBLE
\providecommand{\DIFaddFL}[1]{\DIFadd{#1}} %DIF PREAMBLE
\providecommand{\DIFdelFL}[1]{\DIFdel{#1}} %DIF PREAMBLE
\providecommand{\DIFaddbeginFL}{} %DIF PREAMBLE
\providecommand{\DIFaddendFL}{} %DIF PREAMBLE
\providecommand{\DIFdelbeginFL}{} %DIF PREAMBLE
\providecommand{\DIFdelendFL}{} %DIF PREAMBLE

\begin{document}
\DIFaddbegin \DIFadd{Yyyy „Yyyy“ Yyyy }\DIFaddend X
\end{document}
```
When quotes are written explicitly as \qlqq and \qrqq instead of „ and “ the result looks like this
```tex
\begin{document}
\DIFaddbegin \DIFadd{Yyyy }\glqq \DIFadd{Yyyy}\grqq \DIFadd{Yyyy }\DIFaddend X
\end{document}
```
Changing the original diff-file acoordingly solves the problem. Funny, only the left quotation mark seems to make problems
```tex
\begin{document}
\DIFaddbegin \DIFadd{Yyyy }„\DIFadd{Yyyy“ Yyyy }\DIFaddend X
\end{document}
```

**Comment by ftilmann** [comment]
I cannot reproduce this. Copy/pasting your example and running latexdiff myself I cannot reproduce and get the correct line:
```tex
\DIFaddbegin \DIFadd{Yyyy „Yyyy“ Yyyy }\DIFaddend X
```
It is possible that this depends on the UTF8 processing of perl, or that the copy/pasting is lossy with respect to the exact encoding. I tested with
    This is LATEXDIFF 1.2.0  (Algorithm::Diff 1.15, Perl v5.18.2)
on Linux.
I cannot help you further, I think.

**Comment by felixinc** [comment]
Thanks for the quick reply and yes, that’s the output I get, too. But I cannot compile it with LaTex, LuaLaTex or XeLaTex. Do you can ?

For me, it always fails if there is a "„" or "\glqq" whithin a \DIFadd{…}-statement. So maybe it’s a problem of latex and not of latexdiff. But as it only makes trouble inside a \DIFadd I thought it must have something to do with latexdiff. At least latexdiff could solve the problem if it would handle "„" the same way it does with "\glqq“, i.e. splitting the DIFadd-group into two DIFadds and writing the quotation mark in between.


latexdiff --version
This is LATEXDIFF 1.2.0  (Algorithm::Diff 1.1902, Perl v5.18.2)
  (c) 2004-2016 F J Tilmann

latex --version
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.17; using libpng 1.6.17
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04

**Comment by ftilmann** [comment]
Sorry, I read your posting too quickly and not carefully enough. Yes, I have the same issue. The trouble is somehow with the interplay between the `ulem` package (used for the underlining) and the quotation mark characters. I googled a bit and it seems a known problem:
[http://tex.stackexchange.com/questions/242168/uline-and-german-quotation-marks](url)

* You either use a different markup style without underlining: E.g. use option `-tCFONT`
* Following the suggestion in the linked stack exchange question, replace the quotation marks by `\glqq,\qrqq` commands and tell latexdiff that these commands need protecting by mbox:
So change the new file line to:
```Yyyy \glqq{}Yyyy\grqq{} Yyyy X```
then run
```latexdiff --append-mboxsafecmd=glqq,grqq old.tex news.tex > diff.tex```
(strictly speaking, only `\glqq` fails, but for symmetry I would still do it this way)

Or try to lobby ulem maintainers to fix this

**Comment by ftilmann** [comment]
To add: excluding the quotation marks from the processing similar to \glqq etc would be difficult. It would be possible in principle to convert them internally to \glqq, but I am not sure how robust this would be for different encodings, and also it is pretty easy to write a wrapper that does this conversion outside latexdiff, e.g. using sed.

**Comment by felixinc** [comment]
Ok, I think I'll stick to your solution using sed.
Thank you for your investigation. This information make the issue much clearer.
