### ISSUE TITLE
Trouble with underscored names

### ISSUE THREAD

**Issue by hjkatz** [ftilmann/latexdiff#9]
I'm having trouble properly getting latexdiff v1.0.4 (with the tableenv patch) to behave correctly with how I name variables. I'm writing documentation for an api and as such I have latex code as follows:

        Variables can be named like the following: ``first\_name'', ``last\_name'', ``project_status''

This prints out the following:

Variables can be named like the following: "first_name", "last_name", "project_status"

I have to escape the underscores for latex to print them in the text environment. I also have cases where I'm escaping dollar signs: "this is a \$variable\_name"

When latexdiff runs it's splitting these names into 2 parts as so:

        \DIFdelbegin \DIFdel{\hspace{1em} }\texttt{\DIFdel{<last}%DIFDELCMD < \_name%%%
        \DIFdel{>Jones</last}%DIFDELCMD < \_name%%%

Is there a way around this? I'm comfortable with perl so I can make edits or apply patches if need be. Thanks in advance!

**Comment by SaschaSchuenemann** [comment]
hmm, maybe writing "first{\_}name" and then adding "\_" to the safe command list using  --append-safecmd="_" as cmd-line argument to latexdiff could work.

**Comment by hjkatz** [comment]
That works, thank you!

**Comment by ftilmann** [comment]
Nice of you to close this, but really the solution described is a workaround, and it should work in the form used in your original question.  This is fixed on master now and will be included in release 1.0.5 when this comes out.
Commit  4710d3bbfc74eea6c6592209458302ab591cfb1b
(the \$ command should have been treated correctly on 1.0.4 - in any case it should be fine now)
