### ISSUE TITLE
`\subfloat{\label{a}}` is not completely commented out when deleted

### ISSUE THREAD

**Issue by bersbersbers** [ftilmann/latexdiff#90]
Removing `\subfloat{\label{a}}` from a file results in that final `}` remaining in the diff file, rendering the comparison result uncompilable. Here's an MWE:

[a.txt](https://github.com/ftilmann/latexdiff/files/855896/a.txt)
[b.txt](https://github.com/ftilmann/latexdiff/files/855897/b.txt)
[diff.txt](https://github.com/ftilmann/latexdiff/files/855898/diff.txt)

> This is LATEXDIFF 1.2.1a  (Algorithm::Diff 1.1903, Perl v5.24.0)
>   (c) 2004-2016 F J Tilmann

**Comment by zach-capalbo** [comment]
This also seems to happen with `\mbox{\label{a}}`

**Comment by ftilmann** [comment]
Should be fixed with commit f7814b7
