### ISSUE TITLE
Komaclasses such as scrbook do not define \sf anymore

### ISSUE THREAD

**Issue by kiryph** [ftilmann/latexdiff#92]
When using latexdiff for a file which uses as documentclass `scrbook` the compilation fails with following error:

`Class scrbook Error: undefined old font command '\sf'.`

This can be fixed when adding following to the preamble
```tex
\makeatletter
\DeclareOldFontCommand{\rm}{\normalfont\rmfamily}{\mathrm}
\DeclareOldFontCommand{\sf}{\normalfont\sffamily}{\mathsf}
\DeclareOldFontCommand{\tt}{\normalfont\ttfamily}{\mathtt}
\DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}
\DeclareOldFontCommand{\it}{\normalfont\itshape}{\mathit}
\DeclareOldFontCommand{\sl}{\normalfont\slshape}{\@nomath\sl}
\DeclareOldFontCommand{\sc}{\normalfont\scshape}{\@nomath\sc}
\makeatother
```
However, these style of commands are discouraged to use (see e.g.`l2tabuen.pdf`) and I also do not like to add code just for diffing latex files.

Can latexdiff itself be changed to handle these classes out-of-the-box?

**Comment by ftilmann** [comment]
Are you using `-t CFONT` option? The default markup style does not use \sf command.  You can easily define your own markup commands by using `--preamble` option (start with `show--preamble`` and simply add the command defining `\sf` from your post) . I cannot simply replace `\sf` by `\sffamily` because the same command needs to work both in text and math mode. I guess there is an argument for adding the line `\DeclareOldFontCommand{\sf}{\normalfont\sffamily}{\mathsf}`.  I will probably do this.  I don't think you need the `\makeatletter` and `\makeatother` commands.

**Comment by kiryph** [comment]
Yes, I was using  `CFONT`. Since  only `\sf` is missed by latexdiff, only `\DeclareOldFontCommand{\sf}{\normalfont\sffamily}{\mathsf}` has to be added.

Anyhow, I am no expert and can't judge about side-effects. However, supporting the komaclasses as they stand seems to be a good reason. This would definitely make `latexdiff` more newbie friendly.

I can imagine how difficult it is to maintain a tool such as `latexdiff` in an always changing latex world.
For instance, in order to use `lualatex` and a major mode with `changebars` following things have to be adjusted: `pdftex` driver has to be enabled manually for the package `changebars` and the package `luatex85` must be loaded.

**Comment by ftilmann** [comment]
There does not seem to be any disadvantage to using `\DeclareOldFontCommand` so I added that to all the styles using `\sf` or `\bf` font commands, and will close this issue.  For your comment on luatex please open a separate issue if required. In fact you can implement this your self even without knowing perl by introducing a new type.  The preamble for the different markup types are defined near the end of latexdiff, and you could simply add one for luatex+changebar. If you do so please consider submitting a pull request.
