### ISSUE TITLE
latexdiff-vc --hg fails.

### ISSUE THREAD

**Issue by ouboub** [ftilmann/latexdiff#95]
Hello

I have a directory under hg control which looks like this.
HGGeoIng/.hg
HGGeoIng/Hoja-Teo/h9-edo.tex

so when I run 
usr/local/bin/latexdiff-vc --so --math-markup=3  h9-edo.tex -r 567
I obtain 

Guess you are using CVS ...
Working on  h9-edo.tex
cvs [diff aborted]: /home/oub/cvsroot/CVSROOT: No such file or directory

So I tried 

/usr/local/bin/latexdiff-vc --so --math-markup=3 --hg h9-edo.tex -r 567  
but again 
Guess you are using CVS ...
Working on  h9-edo.tex
cvs [diff aborted]: /home/oub/cvsroot/CVSROOT: No such file or directory

What do I miss

thanks

Uwe Brauer

**Comment by ftilmann** [comment]
This bug is known (issue #93) and has already been fixed in github (commit eff7699 ). (if you are using the version on github rather than the release version, please reopen bug)
