### ISSUE TITLE
feature proposal: add make uninstall

### ISSUE THREAD

**Issue by ouboub** [ftilmann/latexdiff#98]
Hi

I replied to issue 96 which is now closed and therefore I am not sure whether it will be displayed.
Especially for the github version I would like to propose to add

make uninstall

To the makefile

Rationale.

As you said in your reply to issue 96, the github version might be
unstable, so it might be necessary to uninstall it and re install the
stable version.

Installing and uninstalling 3rd party software usually worked nicely on
Debian-like system, because it is relatively easy to generate a deb
package (I presume that rpm based system have a similar functionality).
Then it would be easy to install and uninstall for the latest github
version.

I said it would be. The problem is now that in recent texlive version,
which are shipped by Debian, latexdiff is included, in a way that
uninstall latexdiff would uninstall the whole texlive distribution. I
will most like send a complain about it to the authors, but given my
past experience I don't make myself to many illusions. Maybe that
problem can be circumvent somehow, but I am sure a

 make uninstall

Option would benefit other users as well.

Thanks

Uwe Brauer

**Comment by ftilmann** [comment]
As latexdiff and latexdiff-vc are purposefully scripts without need to access external data files, I would still say there is no real need to uninstall the operating system version of latexdiff, and you can just make copies into your own bin directory (assuming you are on linux or Mac), and set up your path in such a way that the OS installed latexdiff is shadowed by the one in your personal folder. 

Also I think the install makefile is set up in such a way that the existing installation would simply be overwritten (though not really sure on that - the last time I really tested "make install" is many years ago, I am afraid.

I will leave the issue open but I will probably not treat it with high priority.  It should not be difficult to do so maybe I will get round to it sometime or somebody else can provide a pull request
