### ISSUE TITLE
--graphics-markup=0 still allows some (invalid) graphics markup

### ISSUE THREAD

**Issue by bersbersbers** [ftilmann/latexdiff#99]
Changing a `figure*` environment into a `figure` environment introduces a number of `latexdiff` tags around that environment, even though `--graphics-markup=0` is set.

MWE:
[old.tex.txt](https://github.com/ftilmann/latexdiff/files/986912/old.tex.txt)
[new.tex.txt](https://github.com/ftilmann/latexdiff/files/986913/new.tex.txt)

    latexdiff --version
    This is LATEXDIFF 1.2.1a  (Algorithm::Diff 1.1903, Perl v5.24.0)
      (c) 2004-2016 F J Tilmann
    latexdiff --graphics-markup=0 old.tex new.tex > diff.tex

[diff.tex.txt](https://github.com/ftilmann/latexdiff/files/986915/diff.tex.txt)

The environment becomes this:

```
\DIFdelbegin %DIFDELCMD < \begin{figure*}[b]
%DIFDELCMD < 	%%%
\DIFdelendFL \DIFaddbeginFL \begin{figure}[b]
	\DIFaddendFL \includegraphics{example-image-a}
	\caption{CAPTION}
\DIFdelbeginFL %DIFDELCMD < \end{figure*}
%DIFDELCMD <  %%%
\DIFdelend \DIFaddbegin \end{figure}
 \DIFaddend
```

Note that most of the environment is wrapped in `\DIFdelbegin...\DIFdelend` now. Depending on what you `\DIFdelbegin` is (for me, it starts a `comment` environment), this can have unwanted consequences (for me, making the `figure` disappear).

**Comment by bersbersbers** [comment]
Also, note that `DIFdelendFL` appears before the corresponding `\DIFdelbeginFL`.

**Comment by ftilmann** [comment]
The improper nesting is admittedly horrible but would be quite difficult to fix; also it is not quite clear what the right usage should be. I had envisaged the \DIF(add|del)(begin|end) to be mostly for bookkeeping, or maybe to insert a small visual symbol to show invisible changes, but you will probably run into other problems making them into a paired environment (They can occur at different grouping levels, for example). 

If you define `\DIFdelbeginFL` identically to `\DIFdekbegin` and correspondingly for `\DIFdelend` your code snippet should be alright in principle, although I have a feeling that the specificities of the comment environment might conspire against this. 
So as a work-around could be to use `sed` or similar to physically change the `\DIF` tokens into `\begin{comment}` or `\end{comment}`  Does BOLD style not work for you to hide the changed parts?

**Comment by ftilmann** [comment]
I answered mostly to your second comment.  On the first there is a misunderstanding what `--graphics-markup` does.  It is only concerned with markup of images or vector graphics included via \includegraphics` and has nothing to do with figure environments (for suppressing markup in figures, add `figure[*]?` to the environments in PICTUREENV.

Note that I will close this issue for now.  If you feel strongly about the bad nesting being a problem feel free to open a new issue make a proposal how the result should look like in your opinion

**Comment by bersbersbers** [comment]
I don't feel strongly about the nesting since I can avoid the figure environments using `--add-to-config "PICTUREENV=figure[*]?"`. Thanks!
